services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins

    container_name: project123-jenkins
    restart: unless-stopped
    user: root

    ports:
      - "8080:8080"
      - "50000:50000"

    environment:
      TZ: Asia/Seoul

    volumes:
      - jenkins_home:/var/jenkins_home

      # Docker Desktop의 Docker 엔진 사용
      - /var/run/docker.sock:/var/run/docker.sock

      # Windows의 현재 프로젝트를 Jenkins 내부에 연결
      - "C:/Users/KW-20/Desktop/project123:/project123"

volumes:
  jenkins_home: