services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins

    container_name: project123-jenkins
    restart: unless-stopped
    user: root

    ports:
      - "8080:8080"
      - "50000:50000"

    environment:
      TZ: Asia/Seoul

    volumes:
      # Jenkins 데이터
      - jenkins_home:/var/jenkins_home

      # Docker 소켓
      - /var/run/docker.sock:/var/run/docker.sock

      # EC2의 현재 프로젝트를 Jenkins에 마운트
      - /home/ubuntu/n8n_jenkinstest:/project123

volumes:
  jenkins_home: